export const FORM_CHANGE = 'FORM_CHANGE';
export const TABLE_FORM_CHANGE = 'TABLE_FORM_CHANGE';

export const FORM_CHANGE_BASIC = 'FORM_CHANGE_BASIC';
export const FORM_CHANGE_COLLECTION = 'FORM_CHANGE_COLLECTION';
export const FORM_CLEAR = 'FORM_CLEAR';
export const OPERATION_COMPLETED = 'OPERATION_COMPLETED'; //TODO: document why?
export const TILE_FORM_CHANGE = 'TILE_FORM_CHANGE';
export const CT_FORM_CHANGE = 'CT_FORM_CHANGE';  //Compact Tabular Form Change
