export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const CLEAR_SNACKBAR = 'CLEAR_SNACKBAR';
